# JWT Secrets
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-jwt-secret
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: supabase-secret-store
    kind: SecretStore
  target:
    name: supabase-jwt
    creationPolicy: Owner
  data:
  - secretKey: secret
    remoteRef:
      key: supabase/jwt-secrets
      property: jwt_secret
  - secretKey: anonKey
    remoteRef:
      key: supabase/jwt-secrets
      property: anon_key
  - secretKey: serviceKey
    remoteRef:
      key: supabase/jwt-secrets
      property: service_key
---
# Database Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-db-secret
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: supabase-secret-store
    kind: SecretStore
  target:
    name: supabase-db
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: supabase/database-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: supabase/database-credentials
      property: password
---
# SMTP Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-smtp-secret
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: supabase-secret-store
    kind: SecretStore
  target:
    name: supabase-smtp
    creationPolicy: Owner
  data:
  - secretKey: host
    remoteRef:
      key: supabase/smtp-credentials
      property: smtp_host
  - secretKey: port
    remoteRef:
      key: supabase/smtp-credentials
      property: smtp_port
  - secretKey: username
    remoteRef:
      key: supabase/smtp-credentials
      property: smtp_user
  - secretKey: password
    remoteRef:
      key: supabase/smtp-credentials
      property: smtp_password
  - secretKey: from-address
    remoteRef:
      key: supabase/smtp-credentials
      property: smtp_from
---
# Dashboard Credentials
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: supabase-dashboard-secret
  namespace: supabase
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: supabase-secret-store
    kind: SecretStore
  target:
    name: supabase-dashboard
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: supabase/dashboard-credentials
      property: username
  - secretKey: password
    remoteRef:
      key: supabase/dashboard-credentials
      property: password