apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: supabase
  namespace: supabase
spec:
  interval: 15m
  chart:
    spec:
      chart: ./charts/supabase
      sourceRef:
        kind: GitRepository
        name: supabase-community
        namespace: flux-system
  values:
    # JWT Configuration from External Secrets
    jwt:
      existingSecret: supabase-jwt

    # Database Configuration
    db:
      enabled: true
      image:
        tag: "15.1.0.147"
      persistence:
        enabled: true
        size: 20Gi
        storageClass: ebs-sc
      auth:
        existingSecret: supabase-db
        secretKeys:
          adminPasswordKey: password
          userPasswordKey: password
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "2Gi"
          cpu: "2"
      initdbScriptsConfigMap: supabase-db-init

    # Studio Configuration
    studio:
      enabled: true
      replicas: 2
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 5
        targetCPUUtilizationPercentage: 80
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      auth:
        enabled: true
        existingSecret: supabase-dashboard
        secretKeys:
          usernameKey: username
          passwordKey: password

    # Auth Service Configuration
    auth:
      enabled: true
      replicas: 2
      image:
        repository: supabase/gotrue
        tag: "v2.174.0"
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 10
        targetCPUUtilizationPercentage: 70
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "1"
      smtp:
        existingSecret: supabase-smtp
      environment:
        GOTRUE_SMTP_ADMIN_EMAIL: "noreply@${DOMAIN_NAME}"
        GOTRUE_SMTP_SENDER_NAME: "Supabase"
      envFrom:
        - secretRef:
            name: supabase-env-secrets
        - configMapRef:
            name: supabase-env-config

    # REST Service Configuration
    rest:
      enabled: true
      replicas: 3
      image:
        repository: postgrest/postgrest
        tag: "v12.2.12"
      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 20
        targetCPUUtilizationPercentage: 70
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "2"
      envFrom:
        - secretRef:
            name: supabase-env-secrets
        - configMapRef:
            name: supabase-env-config

    # Realtime Service Configuration
    realtime:
      enabled: true
      replicas: 2
      image:
        repository: supabase/realtime
        tag: "v2.34.47"
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 10
        targetCPUUtilizationPercentage: 70
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "2"
      envFrom:
        - secretRef:
            name: supabase-env-secrets
        - configMapRef:
            name: supabase-env-config

    # Storage Service Configuration
    storage:
      enabled: true
      replicas: 2
      image:
        repository: supabase/storage-api
        tag: "v1.23.0"
      persistence:
        enabled: true
        size: 50Gi
        storageClass: ebs-sc
      autoscaling:
        enabled: true
        minReplicas: 2
        maxReplicas: 10
        targetCPUUtilizationPercentage: 80
      resources:
        requests:
          memory: "256Mi"
          cpu: "200m"
        limits:
          memory: "1Gi"
          cpu: "2"
      envFrom:
        - secretRef:
            name: supabase-env-secrets
        - configMapRef:
            name: supabase-env-config

    # Kong API Gateway Configuration
    kong:
      enabled: true
      replicas: 3
      autoscaling:
        enabled: true
        minReplicas: 3
        maxReplicas: 20
        targetCPUUtilizationPercentage: 70
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "4"
      ingress:
        enabled: true
        className: alb
        annotations:
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/target-type: ip
          alb.ingress.kubernetes.io/backend-protocol: HTTP
          alb.ingress.kubernetes.io/healthcheck-path: /health
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
          alb.ingress.kubernetes.io/ssl-redirect: '443'
          alb.ingress.kubernetes.io/certificate-arn: "${ACM_CERTIFICATE_ARN}"
        tls:
          - hosts:
              - supabase.${DOMAIN_NAME}
        hosts:
          - host: supabase.${DOMAIN_NAME}
            paths:
              - path: /
                pathType: Prefix

    # Meta Service Configuration
    meta:
      enabled: true
      replicas: 2
      image:
        repository: supabase/postgres-meta
        tag: "v0.89.3"
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "500m"

    # Functions Service Configuration
    functions:
      enabled: false  # Enable when needed
      
    # Analytics Configuration
    analytics:
      enabled: false  # Enable when needed with proper API keys

    # Vector Configuration for logging
    vector:
      enabled: true
      image:
        repository: timberio/vector
        tag: "0.28.1-alpine"
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "500m"
      existingConfigmap: vector-config

    # MinIO Configuration (using S3 instead)
    minio:
      enabled: false

    # Global configuration
    global:
      postgresqlEnabled: true