apiVersion: v1
kind: ConfigMap
metadata:
  name: account-info
  namespace: aws-${ACCOUNT_ALIAS}
data:
  ACCOUNT_ID: "${ACCOUNT_ID}"
  ACCOUNT_NAME: "${ACCOUNT_NAME:=${ACCOUNT_ALIAS}}"
  ACCOUNT_ALIAS: "${ACCOUNT_ALIAS}"
  ENVIRONMENT: "${ENVIRONMENT}"
  NAMESPACE: "aws-${ACCOUNT_ALIAS}"
  REGION: "${REGION}"