apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vpc.yaml
  - networking-configmap.yaml

configMapGenerator:
  - name: cluster-networking
    namespace: ${ACCOUNT_NAMESPACE}
    literals:
      - CLUSTER_NAME=${CLUSTER_NAME}
      - ACCOUNT_NAME=${ACCOUNT_NAME}
      - REGION=${REGION}

replacements:
  - source:
      kind: ConfigMap
      name: account-info
      fieldPath: data.ACCOUNT_NAME
    targets:
      - select:
          kind: VPC
        fieldPaths:
          - spec.parameters.accountName
  - source:
      kind: ConfigMap
      name: account-info
      fieldPath: data.REGION
    targets:
      - select:
          kind: VPC
        fieldPaths:
          - spec.parameters.region