apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-aws-controller
  namespace: crossplane-system
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/CrossplaneAWSProviderRole"
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |-
    [default]
    role_arn = arn:aws:iam::${AWS_ACCOUNT_ID}:role/CrossplaneAWSProviderRole
    web_identity_token_file = /var/run/secrets/eks.amazonaws.com/serviceaccount/token
---
# This secret will be referenced by the AWS Provider to configure cross-account access
apiVersion: v1
kind: Secret
metadata:
  name: aws-cross-account-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |-
    [default]
    role_arn = arn:aws:iam::${AWS_ACCOUNT_ID}:role/CrossplaneAWSProviderRole
    web_identity_token_file = /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    
    [child-account-1]
    role_arn = arn:aws:iam::111111111:role/CrossplaneProviderRole
    source_profile = default
    
    # Add additional child accounts as needed following the same pattern
    # [child-account-2]
    # role_arn = arn:aws:iam::<CHILD_ACCOUNT_2_ID>:role/CrossplaneProviderRole
    # source_profile = default
