apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-azure
  namespace: crossplane-system
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "${CROSSPLANE_CLIENT_ID}"
    azure.workload.identity/tenant-id: "${AZURE_TENANT_ID}"