apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - crds/
  - crossplane-core.yaml
  - providers/
  - compositions/
  - aws-iam.yaml
  - azure-workload-identity.yaml
  - configurations/

namespace: crossplane-system
