apiVersion: network.example.org/v1alpha1
kind: VPC
metadata:
  name: main
  namespace: aws-test-account-1
spec:
  region: us-west-2
  accountName: test-account-1
  cidrBlock: "10.2.0.0/16"
  publicSubnetCIDRs:
    - "10.2.0.0/24"
    - "10.2.1.0/24"
    - "10.2.2.0/24"
  privateSubnetCIDRs:
    - "10.2.100.0/24"
    - "10.2.101.0/24"
    - "10.2.102.0/24"
  enableDnsSupport: true
  enableDnsHostNames: true