apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: test-account-1
  namespace: crossplane-system
spec:
  credentials:
    source: InjectedIdentity
  assumeRole:
    roleARN: "arn:aws:iam::155090738550:role/OrganizationAccountAccessRole"
---
apiVersion: network.example.org/v1alpha1
kind: VPC
metadata:
  name: test-account-vpc
  namespace: default
spec:
  region: us-east-1
  cidrBlock: "10.2.0.0/16"
  enableDnsSupport: true
  enableDnsHostNames: true
  accountName: test-account-1
  publicSubnetCIDRs:
    - "10.2.0.0/24"
    - "10.2.1.0/24"
  privateSubnetCIDRs:
    - "10.2.2.0/24"
    - "10.2.3.0/24"