apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-efs-csi-driver
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: aws-efs-csi-driver
      version: "2.5.7"
      sourceRef:
        kind: HelmRepository
        name: aws-efs-csi-driver
        namespace: flux-system
  values:
    controller:
      region: us-east-1
      replicaCount: 1
      serviceAccount:
        create: true
        name: efs-csi-controller-sa
        annotations:
          eks.amazonaws.com/role-arn: "${EFS_CSI_ROLE_ARN}"
    node:
      serviceAccount:
        create: true
        name: efs-csi-node-sa
        annotations:
          eks.amazonaws.com/role-arn: "${EFS_CSI_ROLE_ARN}"
    storageClasses:
      - name: efs-sc
        annotations:
          storageclass.kubernetes.io/is-default-class: "false"
        volumeBindingMode: Immediate
        reclaimPolicy: Delete
        parameters:
          provisioningMode: efs-ap
          fileSystemId: ""  # Will need to be set with actual EFS filesystem ID
          directoryPerms: "700"