apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-controller-config
  namespace: crossplane-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::692859948957:role/CrossplaneAWSProviderRole
spec:
  podSecurityContext:
    fsGroup: 2000
  args:
    - --debug
  env:
    - name: AWS_SDK_LOAD_CONFIG
      value: "true"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
---
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: crossplane-system
spec:
  credentials:
    source: InjectedIdentity
---
# Provider config for cross-account access to child account 1
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: child-account-1
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-cross-account-creds
      key: credentials
    # Note: The aws-cross-account-creds secret should contain a credentials file with a child-account-1 profile
