apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-helm
  namespace: crossplane-system
spec:
  package: "xpkg.upbound.io/crossplane-contrib/provider-helm:v0.16.0"
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 3
---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: in-cluster
  namespace: crossplane-system
spec:
  credentials:
    source: InjectedIdentity
