apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: env-test-account-1
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kubernetes/environments/test-account-1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure  # Wait for core infrastructure
  wait: true
  timeout: 30m0s
---
# Separate kustomization for clusters to ensure dependencies are met
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: env-test-account-1-clusters
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kubernetes/environments/test-account-1/clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: env-test-account-1  # Wait for account and networking
  wait: false  # Clusters take a long time, don't block
  timeout: 60m0s