apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - gotk-components.yaml
  - helm-repositories.yaml
  - infrastructure.yaml
  - environments.yaml

# Note: commonLabels removed to prevent deployment selector immutability issues
# Labels can be added to individual resources as needed
