apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aws-test-account-1

resources:
  - networking
  - permissions
  - definition
  - system

configMapGenerator:
  - name: dev-cluster-config
    envs:
      - cluster-config.env