apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crossplane-stable
  namespace: crossplane-system
spec:
  interval: 10m
  url: https://charts.crossplane.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 15m
  chart:
    spec:
      chart: crossplane
      version: "1.14.0"
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: crossplane-system
  values:
    metrics:
      enabled: true
    serviceAccount:
      customAnnotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/CrossplaneControllerRole"
    resourcesCrossplane:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    provider:
      packages: []  # We'll install providers separately
