apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - aws-ebs-csi.yaml
  - cert-manager.yaml
  - cluster-api.yaml
  - crossplane.yaml
  - flux-system.yaml
  - logging.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: fullstack-Cluster
