apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-components
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/base/flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
