apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 15m
  chart:
    spec:
      chart: external-secrets
      version: "0.12.0"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: true
    replicaCount: 1
    leaderElect: false
    serviceAccount:
      create: true
      name: external-secrets-sa
      annotations:
        eks.amazonaws.com/role-arn: "${EXTERNAL_SECRETS_ROLE_ARN}"
    rbac:
      create: true
    webhook:
      replicaCount: 1
      serviceAccount:
        create: true
        name: external-secrets-webhook-sa
        annotations:
          eks.amazonaws.com/role-arn: "${EXTERNAL_SECRETS_ROLE_ARN}"
    certController:
      replicaCount: 1
      serviceAccount:
        create: true
        name: external-secrets-cert-controller-sa
        annotations:
          eks.amazonaws.com/role-arn: "${EXTERNAL_SECRETS_ROLE_ARN}"