apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: logging
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/newaccount/cluster1/logging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system