apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-dev-test-account-1
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kubernetes/environments/test-account-1/clusters/dev-cluster-v2
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: env-test-account-1  # Wait for environment setup
  postBuild:
    substituteFrom:
      # Environment-wide values (VPC, subnets, etc.)
      - kind: ConfigMap
        name: cluster-values
      # Cluster-specific values
      - kind: ConfigMap
        name: dev-cluster-values
  wait: false
  timeout: 60m0s