apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/cluster-templates/eks-cluster.yaml

# Cluster-specific configuration passed as ConfigMap
configMapGenerator:
  - name: dev-cluster-values
    namespace: flux-system
    literals:
      - CLUSTER_NAME=dev-cluster
      - CLUSTER_NAMESPACE=default