apiVersion: v1
kind: Namespace
metadata:
  name: aws-${ACCOUNT_ALIAS}
  labels:
    purpose: aws-account-resources
    toolkit.fluxcd.io/tenant: account
    account.aws/alias: ${ACCOUNT_ALIAS}
    account.aws/environment: ${ENVIRONMENT}