apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: ${ACCOUNT_ALIAS}
spec:
  assumeRoleARN: arn:aws:iam::${ACCOUNT_ID}:role/OrganizationAccountAccessRole
  credentials:
    source: InjectedIdentity