apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/account-namespace  # Base namespace and RBAC
  - account-info.yaml
  - provider-config.yaml
  - iam-roles.yaml
  - cluster-role-identity.yaml