apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: test-account-1
spec:
  credentials:
    source: InjectedIdentity
  assumeRoleARN: arn:aws:iam::137457118074:role/OrganizationAccountAccessRole