apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
spec:
  interval: 5m
  chart:
    spec:
      chart: fluent-bit
      version: "0.39.0"
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
  values:
    config:
      inputs: |
        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            Parser docker
            Tag kube.*
            Mem_Buf_Limit 5MB
            Skip_Long_Lines On
      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
      outputs: |
        [OUTPUT]
            Name es
            Match kube.*
            Host elasticsearch-master
            Port 9200
            HTTP_User ${ELASTICSEARCH_USERNAME}
            HTTP_Passwd ${ELASTICSEARCH_PASSWORD}
            Logstash_Format On
            Retry_Limit False
            Time_Key @timestamp
            Replace_Dots On
            Suppress_Type_Name On
            tls On
            tls.verify On
            tls.ca_file /certs/ca.crt
            tls.crt_file /certs/tls.crt
            tls.key_file /certs/tls.key
    extraVolumeMounts:
      - name: es-certs
        mountPath: /certs
        readOnly: true
    extraVolumes:
      - name: es-certs
        secret:
          secretName: elasticsearch-master-certs
    env:
      - name: ELASTICSEARCH_USERNAME
        valueFrom:
          secretKeyRef:
            name: elasticsearch-master-credentials
            key: username
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-master-credentials
            key: password
