apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: elastic
  namespace: logging
spec:
  interval: 1h
  url: https://helm.elastic.co
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluent
  namespace: logging
spec:
  interval: 1h
  url: https://fluent.github.io/helm-charts