apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: logging
spec:
  interval: 5m
  chart:
    spec:
      chart: kibana
      version: "8.5.1"  # Matching Elasticsearch version
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
  values:
    env:
      - name: ELASTICSEARCH_USERNAME
        valueFrom:
          secretKeyRef:
            name: elasticsearch-master-credentials
            key: username
      - name: ELASTICSEARCH_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-master-credentials
            key: password