apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-test-cluster-values
  namespace: aws-test-account-1
data:
  CLUSTER_NAME: "gitops-test-cluster"
  CLUSTER_NAMESPACE: "default"
  NODEGROUP_NAME: "gitops-test-cluster-ng-0"
  MACHINE_POOL_NAME: "gitops-test-cluster-pool-0"
  MIN_SIZE: "1"
  MAX_SIZE: "3"
  INSTANCE_TYPE: "t3.medium"
