apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-master-credentials
  namespace: logging
type: Opaque
data:
  username: ZWxhc3RpYw==  # base64 encoded 'elastic'
  password: ZWxhc3RpYw==  # base64 encoded 'elastic'
---
# TODO: kibana/elasticsearch username/password
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: logging
type: Opaque
data:
  username: ZWxhc3RpYw==  # base64 encoded 'elastic'
  password: ZWxhc3RpYw==  # base64 encoded 'elastic'
