apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
  - namespace.yaml
  - elasticsearch.yaml
  - kibana.yaml
  - fluent-bit.yaml

commonLabels:
  app.kubernetes.io/component: logging
