apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: CLUSTER-NAME-pool-0
spec:
  clusterName: CLUSTER-NAME
  replicas: 2
  template:
    spec:
      clusterName: CLUSTER-NAME
      bootstrap:
        dataSecretName: ""
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: CLUSTER-NAME-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: CLUSTER-NAME-pool-0
spec:
  roleAdditionalPolicies:
    - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  roleName: eks-nodegroup.cluster-api-provider-aws.sigs.k8s.io
  scaling:
    minSize: 1
    maxSize: 3
  instanceType: t3.medium
  eksNodegroupName: CLUSTER-NAME-ng-0