apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # System components
  - aws-ebs-csi.yaml
  - cert-manager.yaml
  - external-secrets.yaml
  - aws-load-balancer-controller.yaml
  - monitoring.yaml
  - logging.yaml
  # Note: flux-system is managed by flux bootstrap, not included here

  - crossplane.yaml
  - cluster-api.yaml
  
  # Applications
