apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/cluster-templates/eks-cluster-configmap-refs.yaml

configMapGenerator:
  - name: test-cluster-values
    namespace: flux-system
    # Static values
    literals:
      - CLUSTER_NAME=test-cluster
      - CLUSTER_NAMESPACE=default
      - NODE_INSTANCE_TYPE=t3.medium
      - NODE_MIN_SIZE=1
      - NODE_MAX_SIZE=3
      - NODE_DESIRED_SIZE=2
    # Dynamic values from generate-cluster-config.sh
    envs:
      - cluster-config.env