apiVersion: v1
kind: ServiceAccount
metadata:
  name: capa-controller-manager
  namespace: cluster-api-system
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/ClusterAPIControllerRole"
---
apiVersion: v1
kind: Secret
metadata:
  name: capa-manager-bootstrap-credentials
  namespace: cluster-api-system
stringData:
  credentials: |-
    [default]
    role_arn = arn:aws:iam::${AWS_ACCOUNT_ID}:role/ClusterAPIControllerRole
    web_identity_token_file = /var/run/secrets/eks.amazonaws.com/serviceaccount/token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capa-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-api-provider-aws-manager-role
subjects:
- kind: ServiceAccount
  name: capa-controller-manager
  namespace: cluster-api-system
