apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: infrastructure-aws
  namespace: cluster-api-system
spec:
  interval: 10m
  url: https://kubernetes-sigs.github.io/cluster-api-provider-aws
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: infrastructure-aws
  namespace: cluster-api-system
spec:
  interval: 15m
  chart:
    spec:
      chart: capa
      version: "2.3.0"
      sourceRef:
        kind: HelmRepository
        name: infrastructure-aws
        namespace: cluster-api-system
  values:
    manager:
      featureGates:
        ClusterTopology: true
    assumeRole: true  # Enabling IAM roles for service accounts
    # Configure AWS cross-account role assumption
    awsClusterControllerIdentity:
      allowedNamespaces:
        list:
          - "cluster-api-system"
          - "default"
      trustIdentity: {}  # This will use the default controller identity
    eks:
      iamAuthenticator:
        enabled: false  # Not using EKS
