apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - core-components.yaml
  - bootstrap-kubeadm-components.yaml
  - control-plane-kubeadm-components.yaml
  - infrastructure-aws-components.yaml
  - capa-irsa-role.yaml
  - aws-identity-provider.yaml
  
# Note: Different components use different namespaces:
# - cluster-api-system for core components
# - capi-kubeadm-bootstrap-system for bootstrap provider
# - capi-kubeadm-control-plane-system for control plane provider  
# - capa-system for AWS infrastructure provider
