apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - crds/
  - cluster-api-core.yaml
  - bootstrap-kubeadm.yaml
  - control-plane-kubeadm.yaml
  - infrastructure-aws.yaml
  - aws-controller-iam.yaml
  - aws-identity-provider.yaml
  
namespace: cluster-api-system
