apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcapaiamroles.aws.platform.io
spec:
  group: aws.platform.io
  names:
    kind: XCAPAIAMRoles
    plural: xcapaiamroles
  claimNames:
    kind: CAPAIAMRoles
    plural: capaiamroles
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              region:
                type: string
                description: AWS region to create IAM roles in
                default: us-west-2
              providerConfigRef:
                type: object
                properties:
                  name:
                    type: string
                required:
                - name
              accountId:
                type: string
                description: AWS Account ID where roles will be created
              tags:
                type: object
                additionalProperties:
                  type: string
                description: Tags to apply to all resources
            required:
            - providerConfigRef
            - accountId
          status:
            type: object
            properties:
              eksControlPlaneRoleArn:
                type: string
                description: ARN of the EKS control plane role
              eksNodeGroupRoleArn:
                type: string
                description: ARN of the EKS node group role
              controlPlaneInstanceProfileName:
                type: string
                description: Name of the control plane instance profile
              nodesInstanceProfileName:
                type: string
                description: Name of the nodes instance profile