apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/{{ management }}/{{ primary }}/system/external-secrets
  prune: true
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: terraform-outputs